Update Deploy-to-ecs-ec2.yaml

diff --git a/.github/workflows/Deploy-to-ecs-ec2.yaml b/.github/workflows/Deploy-to-ecs-ec2.yaml
--- a/.github/workflows/Deploy-to-ecs-ec2.yaml
+++ b/.github/workflows/Deploy-to-ecs-ec2.yaml
@@ -36,16 +36,21 @@ jobs:
           TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition demo-app-task)
           echo "$TASK_DEFINITION" > current_task_definition.json
 
-      - name: Create New Task Definition JSON
-        id: create_task_def
+      - name: Deploy New Task Definition to ECS Service
         run: |
-          # Create a new task definition based on the current one, ensuring to filter out unwanted parameters
-          NEW_TASK_DEF=$(jq --arg IMAGE_URI "${{ env.LATEST_IMAGE_URI }}" \
-            '.taskDefinition | 
-            .containerDefinitions[0].image=$IMAGE_URI |
-            del(.revision, .taskDefinitionArn, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
-            current_task_definition.json)
-          echo "$NEW_TASK_DEF" > new_task_definition.json
+          aws ecs update-service \
+            --cluster example-ecs-cluster \
+            --service example-ecs-service \
+            --force-new-deployment \
+            --task-definition ${{ env.TASK_DEFINITION_ARN }}
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to update ECS service."
+            exit 1
+          fi
+
+      - name: Cleanup Temporary Files
+        run: |
+          rm -f current_task_definition.json new_task_definition.json
 
       - name: Print New Task Definition
         run: cat new_task_definition.json
